# Generated by Django 5.1.6 on 2025-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
