# Generated by Django 5.1.6 on 2025-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Snote', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
