# Generated by Django 5.1.6 on 2025-03-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sticky_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticky_notes',
            name='Snote',
            field=models.CharField(max_length=100),
        ),
    ]
