# Generated by Django 5.1.4 on 2025-04-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_notes_user_sticky_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
